name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on new SemVer tags
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/go-publish.yml@master
    secrets: inherit
    with:
      linux-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w'
      windows-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w'
      macos-build-args: -tags='timetzdata netgo' -trimpath -a -ldflags '-s -w'
      cgo-enabled: 1
      project: troubleshootd
      project-desc: "troubleshootd: Secure storage and signing for seeds"
      version-tag: ${{ github.ref_name }}
